services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend-app-spe
    ports:
      - "8080:8080"
    volumes:
      - backend-vol:/home/app/src/main/resources/logs
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/api/spe/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
volumes:
  backend-vol:
