INSERT INTO SPE_SCHEMA.SPE_CODES (CODE, DESC)
    VALUES ('ORS001', 'Order not sent');
INSERT INTO SPE_SCHEMA.SPE_CODES (CODE, DESC)
    VALUES ('ORS002', 'Order pending');
INSERT INTO SPE_SCHEMA.SPE_CODES (CODE, DESC)
    VALUES ('ORS003', 'Order sent and approved');
INSERT INTO SPE_SCHEMA.SPE_CODES (CODE, DESC)
    VALUES ('ORS004', 'Order not accepted');